// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://secfpyscqomiccywtnbs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNlY2ZweXNjcW9taWNjeXd0bmJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyOTk1NDksImV4cCI6MjA2Mjg3NTU0OX0.zAcRMLNknxAUqoWszAXph8JKR71nbbAyzbsLXiVfKwM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);